version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"

  api01: &api
    hostname: api01
    build:
      context: ./api/
    depends_on:
      - postgres
    environment:
      - HTTP_PORT=3000
      - DATABASE_URL=postgres://docker:docker@localhost:5432/rinha_db
    ports:
      - "3000:3000"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3001:3000"

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rinha_db
    volumes:
      - rinha_db:/bitnami/postgresql

volumes:
  rinha_db:

networks:
  default:
    driver: bridge
    name: rinha_network
